import os
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

def apply_style(run, bold=False, italic=False, size=13):
    run.font.name = 'Times New Roman'
    run.font.size = Pt(size)
    run.bold = bold
    run.italic = italic

def add_heading(doc, text, level):
    p = doc.add_paragraph()
    p.paragraph_format.space_after = Pt(6)
    p.paragraph_format.space_before = Pt(6)
    run = p.add_run(text)
    if level == 0: # Chapter Title
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        apply_style(run, bold=True, size=15)
    elif level == 1: # 3.1
        apply_style(run, bold=True, size=13)
    elif level == 2: # 3.1.1
        apply_style(run, bold=True, size=13)
    elif level == 3: # 3.1.1.1
        apply_style(run, bold=True, italic=True, size=13)

def add_paragraph(doc, text, italic=False, bold=False):
    p = doc.add_paragraph()
    p.paragraph_format.first_line_indent = Pt(36) # ~1.27cm
    p.paragraph_format.space_after = Pt(6)
    p.paragraph_format.line_spacing = 1.3
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    run = p.add_run(text)
    apply_style(run, size=13, italic=italic, bold=bold)

def add_bullet(doc, text):
    p = doc.add_paragraph(style='List Bullet')
    p.paragraph_format.space_after = Pt(6)
    p.paragraph_format.line_spacing = 1.3
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    run = p.add_run(text)
    apply_style(run, size=13)

def create_chuong3():
    doc = Document()
    
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Times New Roman'
    font.size = Pt(13)
    
    add_heading(doc, "CHƯƠNG III. PHÂN TÍCH VÀ THIẾT KẾ HỆ THỐNG", 0)

    add_heading(doc, "3.1 PHÂN TÍCH YÊU CẦU VÀ PHẠM VI HỆ THỐNG", 1)
    add_heading(doc, "3.1.1 Mục tiêu của hệ thống web bài giảng", 2)
    add_paragraph(doc, "Hệ thống web bài giảng LETSCODE được xây dựng nhằm đáp ứng các mục tiêu sau:")
    add_bullet(doc, "Quản lý tập trung các chương trình đào tạo và khóa học")
    add_bullet(doc, "Quản lý bài giảng và nội dung học tập một cách có hệ thống")
    add_bullet(doc, "Hỗ trợ giáo viên trong việc xây dựng và phân phối nội dung giảng dạy")
    add_bullet(doc, "Tạo nền tảng kết nối giữa backend và frontend thông qua API")
    add_paragraph(doc, "Để đạt được các mục tiêu trên, hệ thống backend đóng vai trò then chốt trong việc xử lý nghiệp vụ, lưu trữ dữ liệu và cung cấp dữ liệu cho frontend.")
    add_paragraph(doc, "Qua việc xây dựng hệ thống này, backend đóng vai trò trung tâm trong việc tổ chức và quản lý nội dung học tập, đồng thời đảm nhiệm chức năng xử lý nghiệp vụ và lưu trữ dữ liệu. Backend cũng là cầu nối quan trọng giúp frontend có thể truy xuất và hiển thị dữ liệu một cách nhất quán, phục vụ cho hoạt động giảng dạy của giáo viên.")

    add_heading(doc, "3.2 PHÂN TÍCH VÀ THIẾT KẾ CƠ SỞ DỮ LIỆU", 1)
    add_heading(doc, "3.2.1 Mục tiêu thiết kế cơ sở dữ liệu", 2)
    add_paragraph(doc, "Cơ sở dữ liệu được xây dựng nhằm phục vụ hệ thống giảng dạy Robotics tại Công ty Let’s Code. Đây là hệ thống đào tạo dành cho trẻ em, trong đó nội dung học tập không chỉ bao gồm lý thuyết mà còn bao gồm hướng dẫn lắp ráp mô hình, khối lệnh lập trình, tài liệu minh họa và các bài kiểm tra đánh giá.")
    add_paragraph(doc, "Vì vậy, mục tiêu của việc thiết kế cơ sở dữ liệu bao gồm:")
    add_bullet(doc, "Lưu trữ có hệ thống toàn bộ nội dung giảng dạy Robotics")
    add_bullet(doc, "Chuẩn hóa dữ liệu để tránh trùng lặp, sai lệch hoặc thất lạc")
    add_bullet(doc, "Bảo đảm sự liên kết giữa các đối tượng như chương trình học, khóa học, bài học, người dạy và tài nguyên giảng dạy")
    add_bullet(doc, "Hỗ trợ công tác quản lý và vận hành giảng dạy của phòng Giáo vụ")
    add_bullet(doc, "Tạo nền tảng kỹ thuật để hệ thống có thể mở rộng trong tương lai")
    add_paragraph(doc, "Việc thiết kế cơ sở dữ liệu đúng ngay từ đầu giúp phòng Giáo vụ:")
    add_bullet(doc, "Dễ dàng cập nhật, sửa đổi nội dung đào tạo")
    add_bullet(doc, "Đảm bảo thống nhất giữa các khóa học")
    add_bullet(doc, "Kiểm soát chất lượng dạy và học")
    add_bullet(doc, "Lưu trữ lịch sử giảng dạy phục vụ đánh giá và cải tiến chương trình")
    add_paragraph(doc, "Do đó, công tác phân tích và thiết kế cơ sở dữ liệu được xem là một nhiệm vụ mang tính nền tảng trong quá trình phát triển hệ thống.")

    add_heading(doc, "3.2.2 Tổng quan cấu trúc cơ sở dữ liệu", 2)
    add_paragraph(doc, "Cơ sở dữ liệu được xây dựng theo mô hình cơ sở dữ liệu quan hệ, với tổng số 22 bảng. Các bảng được chia thành các nhóm chức năng như sau:")
    add_bullet(doc, "Nhóm quản lý người dùng và phân công giảng dạy")
    add_bullet(doc, "Nhóm quản lý chương trình, khóa học và bài học")
    add_bullet(doc, "Nhóm quản lý nội dung chi tiết của bài học")
    add_bullet(doc, "Nhóm quản lý câu hỏi và đáp án trắc nghiệm")
    add_bullet(doc, "Nhóm quản lý tiến trình học tập của học sinh")
    add_bullet(doc, "Nhóm quản lý tài nguyên đa phương tiện")
    add_bullet(doc, "Nhóm quản lý khối lệnh lập trình")
    add_bullet(doc, "Nhóm quản lý thẻ phân loại nội dung")
    add_paragraph(doc, "Việc phân nhóm này nhằm phản ánh rõ ràng các khối nghiệp vụ khác nhau trong hệ thống đào tạo, đồng thời giúp cơ sở dữ liệu giữ được cấu trúc dễ hiểu, dễ bảo trì và dễ mở rộng.")

    add_heading(doc, "3.2.3 Nguyên tắc thiết kế và chuẩn hóa dữ liệu", 2)
    add_paragraph(doc, "Cơ sở dữ liệu được thiết kế theo nguyên tắc chuẩn hóa đến dạng chuẩn ba (Third Normal Form – 3NF).")
    add_paragraph(doc, "Điều này có nghĩa là:")
    add_bullet(doc, "Không có trùng lặp dữ liệu không cần thiết")
    add_bullet(doc, "Mỗi bảng chỉ lưu một loại thông tin")
    add_bullet(doc, "Mọi thuộc tính phụ thuộc khóa chính")
    add_bullet(doc, "Dữ liệu nhất quán và dễ bảo trì")
    add_paragraph(doc, "Ví dụ:")
    add_paragraph(doc, "Nếu lưu tên giáo viên trực tiếp trong bảng khóa học thì khi giáo viên đổi tên, toàn bộ bảng phải cập nhật. Điều này có thể gây lỗi dữ liệu. Do đó, giáo viên được lưu riêng, và quan hệ chỉ liên kết theo khóa ngoại.")
    add_paragraph(doc, "Trong quá trình thiết kế cơ sở dữ liệu, nhóm nghiên cứu tuân theo nguyên tắc chuẩn hóa đến dạng chuẩn 3 (Third Normal Form – 3NF) nhằm loại bỏ dư thừa dữ liệu và đảm bảo mỗi bảng chỉ lưu trữ một loại thông tin độc lập.")
    add_paragraph(doc, "Trong giai đoạn đầu, nhóm từng thiết kế bảng Khóa học vừa lưu thông tin khóa học, vừa lưu cả tên giáo viên phụ trách chính. Tuy nhiên, điều này dẫn đến việc cùng một giáo viên xuất hiện lặp lại ở nhiều dòng khác nhau, gây dư thừa dữ liệu và khó cập nhật khi có thay đổi. Sau khi rà soát lại theo nguyên tắc 3NF, nhóm tách thông tin giáo viên sang bảng riêng và sử dụng khóa ngoại để liên kết giữa hai bảng. Nhờ vậy, cấu trúc dữ liệu trở nên gọn hơn và dễ bảo trì hơn.")

    add_heading(doc, "3.2.4 Phân tích chi tiết từng nhóm bảng", 2)
    add_heading(doc, "3.2.4.1 Nhóm quản lý người dùng và phân công giảng dạy", 3)
    add_paragraph(doc, "Nhóm này bao gồm ba bảng:")
    add_bullet(doc, "users")
    add_bullet(doc, "assignments")
    add_bullet(doc, "assignment_logs")
    add_paragraph(doc, "Nhóm này quản lý thông tin người dùng và quy trình phân công giảng dạy. Mỗi bảng đảm nhiệm một cấp quản lý riêng và có liên kết chặt chẽ với nhau nhằm đảm bảo tính nhất quán của hệ thống đào tạo.")

    add_heading(doc, "3.2.4.2 Nhóm chương trình – khóa học – bài học", 3)
    add_paragraph(doc, "Gồm ba bảng:")
    add_bullet(doc, "programs")
    add_bullet(doc, "courses")
    add_bullet(doc, "lessons")
    add_paragraph(doc, "Nhóm này quản lý cấu trúc nội dung đào tạo theo cấp bậc từ chương trình, khóa học đến từng bài học. Mỗi bảng đảm nhiệm một cấp quản lý riêng và có liên kết chặt chẽ với nhau nhằm đảm bảo tính nhất quán của hệ thống đào tạo.")
    add_paragraph(doc, "Việc tổ chức theo thứ bậc:")
    add_paragraph(doc, "Chương trình → Khóa học → Bài học")
    add_paragraph(doc, "giúp nội dung đào tạo có cấu trúc rõ ràng và logic.")

    add_heading(doc, "3.2.4.3 Nhóm bảng mô tả nội dung chi tiết bài học", 3)
    add_paragraph(doc, "Nhóm này gồm:")
    add_bullet(doc, "lesson_objectives")
    add_bullet(doc, "lesson_preparation")
    add_bullet(doc, "lesson_contents")
    add_bullet(doc, "lesson_challenges")
    add_bullet(doc, "lesson_models")
    add_bullet(doc, "lesson_builds")
    add_paragraph(doc, "Mỗi bảng đảm nhiệm một loại nội dung riêng nhưng đều liên kết với bảng lessons.")
    add_paragraph(doc, "Nhóm này bao gồm các bảng quản lý mục tiêu đào tạo, nội dung lý thuyết, hoạt động thực hành và các thành phần chi tiết khác của bài học. Dữ liệu trong nhóm giúp mô tả đầy đủ nội dung giảng dạy của từng bài học.")

    add_heading(doc, "3.2.4.4 Nhóm câu hỏi và đáp án", 3)
    add_paragraph(doc, "Gồm hai bảng:")
    add_bullet(doc, "lesson_quizzes")
    add_bullet(doc, "quiz_answers")
    add_paragraph(doc, "Nhóm này lưu trữ câu hỏi, đáp án và mối quan hệ giữa chúng với từng bài học. Cấu trúc dữ liệu cho phép một câu hỏi có thể có nhiều đáp án và hỗ trợ việc đánh giá kết quả học tập.")

    add_heading(doc, "3.2.4.5 Nhóm phương tiện đa phương tiện", 3)
    add_paragraph(doc, "Gồm:")
    add_bullet(doc, "media")
    add_bullet(doc, "content_media")
    add_paragraph(doc, "Nhóm này quản lý các tài nguyên như hình ảnh, video và tài liệu minh họa được sử dụng trong chương trình đào tạo. Các tài nguyên được liên kết với bài học hoặc hoạt động cụ thể để đảm bảo khả năng tra cứu và sử dụng thuận tiện.")

    add_heading(doc, "3.2.4.6 Nhóm khối lệnh lập trình và thẻ phân loại nội dung", 3)
    add_paragraph(doc, "Gồm:")
    add_bullet(doc, "code_blocks")
    add_bullet(doc, "content_code_blocks")
    add_bullet(doc, "tags")
    add_bullet(doc, "tag_map")
    add_paragraph(doc, "Nhóm này dùng để lưu trữ thông tin về các khối lệnh lập trình và hệ thống thẻ phân loại, giúp phân loại và tổ chức nội dung đào tạo theo từng chủ đề, loại hoạt động hoặc mức độ.")

    add_heading(doc, "3.2.4.7 Nhóm quản lý tiến trình học tập của học sinh", 3)
    add_paragraph(doc, "Gồm:")
    add_bullet(doc, "enrollments")
    add_bullet(doc, "lesson_progress")
    add_paragraph(doc, "Nhóm này đảm nhiệm việc ghi nhận dữ liệu học tập của học sinh. Bảng enrollments quản lý danh sách học sinh đăng ký và tham gia khóa học, trong khi bảng lesson_progress theo dõi tiến trình học từng bài, lưu trữ trạng thái nộp bài tập thực hành và điểm số đánh giá từ giáo viên hoặc hệ thống tự động.")

    add_heading(doc, "3.3 THIẾT KẾ KIẾN TRÚC BACKEND HỆ THỐNG", 1)
    add_heading(doc, "3.3.1 Lựa chọn công nghệ", 2)
    add_paragraph(doc, "Trong quá trình thiết kế backend, nhóm nghiên cứu lựa chọn các công nghệ sau:")
    add_bullet(doc, "Node.js: làm nền tảng chạy server, phù hợp cho việc xây dựng API nhẹ, xử lý bất đồng bộ tốt và dễ mở rộng hệ thống.")
    add_bullet(doc, "TypeScript: giúp kiểm soát kiểu dữ liệu chặt chẽ, giảm lỗi trong quá trình phát triển và thuận lợi khi làm việc nhóm.")
    add_bullet(doc, "Supabase: được sử dụng để quản lý cơ sở dữ liệu, hỗ trợ truy vấn nhanh và tích hợp thuận tiện với backend.")
    add_bullet(doc, "Postman: phục vụ kiểm thử API trong quá trình phát triển, giúp kiểm tra luồng dữ liệu và phát hiện lỗi sớm.")
    add_bullet(doc, "Git: dùng để quản lý mã nguồn, theo dõi lịch sử thay đổi và hỗ trợ làm việc nhóm hiệu quả.")
    add_paragraph(doc, "Việc lựa chọn các công nghệ trên giúp hệ thống backend đảm bảo tính hiện đại, linh hoạt và phù hợp với yêu cầu thực tế của dự án.")

    add_heading(doc, "3.3.2 Mô hình kiến trúc backend", 2)
    add_paragraph(doc, "Backend được thiết kế theo mô hình phân tầng, bao gồm các thành phần sau:")
    add_bullet(doc, "Routes: Định nghĩa đường dẫn API")
    add_bullet(doc, "Controllers: Tiếp nhận và xử lý request")
    add_bullet(doc, "Services: Xử lý logic nghiệp vụ")
    add_bullet(doc, "Models: Tương tác với cơ sở dữ liệu")
    add_bullet(doc, "Middlewares: Xử lý xác thực và phân quyền")
    add_bullet(doc, "Validators: Kiểm tra dữ liệu đầu vào")
    add_paragraph(doc, "Mô hình này giúp mã nguồn dễ đọc, dễ bảo trì và thuận tiện cho làm việc nhóm. Ban đầu nhóm nghiên cứu gặp khó khăn trong việc phân tách vai trò giữa controller và service, đặc biệt khi xử lý các nghiệp vụ phức tạp. Tuy nhiên, sau khi triển khai và điều chỉnh trong quá trình phát triển thực tế, nhóm nghiên cứu nhận thấy mô hình phân tầng giúp mã nguồn dễ quản lý hơn, giảm sự phụ thuộc giữa các thành phần và thuận lợi cho việc mở rộng hệ thống.")

    add_heading(doc, "3.3.3 Xác định các chức năng chính của Backend", 2)
    add_paragraph(doc, "Thông qua quá trình phân tích yêu cầu, backend của hệ thống cần đảm nhiệm các chức năng chính sau:")
    add_bullet(doc, "Quản lý chương trình học")
    add_bullet(doc, "Quản lý khóa học")
    add_bullet(doc, "Quản lý bài giảng")
    add_bullet(doc, "Quản lý nội dung bài học")
    add_bullet(doc, "Quản lý tài nguyên đính kèm")
    add_bullet(doc, "Quản lý người dùng và phân quyền")
    add_paragraph(doc, "Mỗi chức năng được xây dựng thành các API riêng biệt, đảm bảo tính rõ ràng và dễ mở rộng.")
    add_paragraph(doc, "Trong các chức năng trên, nhóm trực tiếp xây dựng đầy đủ API cho quản lý khóa học, bài giảng và nội dung bài học.")
    add_paragraph(doc, "Cách tổ chức này giúp hệ thống backend có cấu trúc rõ ràng, dễ theo dõi luồng xử lý và thuận lợi cho việc phân công, phát triển.")

    add_heading(doc, "3.3.4 Mô tả chi tiết các service backend đã xây dựng", 2)
    add_paragraph(doc, "Trong quá trình nghiên cứu cơ sở lý thuyết, nhóm nghiên cứu trực tiếp thiết kế và triển khai hệ thống backend theo mô hình phân tầng, trong đó tầng Service đóng vai trò trung tâm trong việc xử lý toàn bộ logic nghiệp vụ của hệ thống. Mỗi service được xây dựng tương ứng với một nhóm chức năng cụ thể, giúp mã nguồn có cấu trúc rõ ràng, dễ bảo trì và thuận tiện cho việc mở rộng trong tương lai.")
    add_paragraph(doc, "Các service được tổ chức trong thư mục services, mỗi file đảm nhiệm một chức năng nghiệp vụ độc lập và được controller gọi đến khi xử lý request từ frontend.")

    add_heading(doc, "3.3.4.1 User Service (user.service.ts)", 3)
    add_paragraph(doc, "User Service chịu trách nhiệm xử lý toàn bộ các nghiệp vụ liên quan đến người dùng trong hệ thống. Service này làm việc trực tiếp với cơ sở dữ liệu thông qua Supabase để quản lý thông tin tài khoản và quyền truy cập.")
    add_paragraph(doc, "Các chức năng chính bao gồm:")
    add_bullet(doc, "Tạo và quản lý tài khoản người dùng")
    add_bullet(doc, "Truy vấn danh sách người dùng")
    add_bullet(doc, "Cập nhật thông tin người dùng")
    add_bullet(doc, "Hỗ trợ phân quyền theo vai trò")
    add_paragraph(doc, "Service này đóng vai trò nền tảng cho toàn bộ hệ thống, vì hầu hết các chức năng khác đều phụ thuộc vào thông tin người dùng.")
    add_paragraph(doc, "Service này giúp nhóm hiểu rõ hơn cách tách logic nghiệp vụ liên quan đến quản lý người dùng trong backend.")

    add_heading(doc, "3.3.4.2 Auth Service (auth.service.ts)", 3)
    add_paragraph(doc, "Auth Service được xây dựng để xử lý các nghiệp vụ liên quan đến xác thực và đăng nhập hệ thống. Service này đảm bảo chỉ những người dùng hợp lệ mới có thể truy cập vào các chức năng backend.")
    add_paragraph(doc, "Các chức năng chính:")
    add_bullet(doc, "Xác thực người dùng khi đăng nhập")
    add_bullet(doc, "Kiểm tra thông tin đăng nhập")
    add_bullet(doc, "Hỗ trợ tạo và xác minh token")
    add_bullet(doc, "Kết hợp với middleware để bảo vệ API")
    add_paragraph(doc, "Auth Service góp phần đảm bảo tính bảo mật cho toàn bộ hệ thống backend.")
    add_paragraph(doc, "Service này giúp nhóm hiểu rõ hơn cách tách logic nghiệp vụ liên quan đến xác thực và bảo mật API.")

    add_heading(doc, "3.3.4.3 Permission Service (permission.service.ts)", 3)
    add_paragraph(doc, "Permission Service chịu trách nhiệm kiểm soát quyền truy cập của người dùng đối với từng chức năng trong hệ thống. Service này được sử dụng kết hợp với middleware để thực hiện phân quyền.")
    add_paragraph(doc, "Các chức năng chính:")
    add_bullet(doc, "Xác định quyền truy cập của người dùng")
    add_bullet(doc, "Kiểm tra vai trò trước khi cho phép truy cập API")
    add_bullet(doc, "Hỗ trợ phân quyền động theo chức năng")
    add_paragraph(doc, "Service này giúp hệ thống đảm bảo tính nhất quán và an toàn trong việc phân quyền và giúp nhóm hiểu rõ hơn cách triển khai phân quyền linh hoạt trong backend.")

    add_heading(doc, "3.3.4.4 Program Service (program.service.ts)", 3)
    add_paragraph(doc, "Program Service được xây dựng để quản lý các chương trình đào tạo trong hệ thống. Đây là tầng cao nhất trong cấu trúc nội dung đào tạo.")
    add_paragraph(doc, "Các chức năng chính:")
    add_bullet(doc, "Tạo mới và cập nhật chương trình đào tạo")
    add_bullet(doc, "Truy vấn danh sách chương trình")
    add_bullet(doc, "Quản lý trạng thái chương trình")
    add_paragraph(doc, "Program Service đóng vai trò định hướng cấu trúc đào tạo tổng thể cho toàn bộ hệ thống.")
    add_paragraph(doc, "Service này giúp nhóm hiểu rõ hơn cách tổ chức dữ liệu theo cấu trúc phân cấp.")

    add_heading(doc, "3.3.4.5 Course Service (course.service.ts)", 3)
    add_paragraph(doc, "Course Service chịu trách nhiệm quản lý các khóa học thuộc từng chương trình đào tạo. Service này giúp liên kết chương trình đào tạo với nội dung bài giảng cụ thể.")
    add_paragraph(doc, "Các chức năng chính:")
    add_bullet(doc, "Tạo, cập nhật và xóa khóa học")
    add_bullet(doc, "Truy vấn khóa học theo chương trình")
    add_bullet(doc, "Cung cấp dữ liệu khóa học cho frontend")
    add_paragraph(doc, "Service này giúp nhóm hiểu rõ hơn mối quan hệ giữa chương trình đào tạo và khóa học.")

    add_heading(doc, "3.3.4.6 Lesson Service (lesson.service.ts)", 3)
    add_paragraph(doc, "Lesson Service quản lý thông tin bài giảng trong từng khóa học, bao gồm tiêu đề, mô tả và thứ tự hiển thị.")
    add_paragraph(doc, "Các chức năng chính:")
    add_bullet(doc, "Tạo và cập nhật bài giảng")
    add_bullet(doc, "Truy vấn danh sách bài giảng")
    add_bullet(doc, "Quản lý mối quan hệ giữa bài giảng và khóa học")
    add_paragraph(doc, "Service này giúp nhóm hiểu rõ hơn cách liên kết dữ liệu giữa bài giảng và khóa học.")

    add_heading(doc, "3.3.4.7 LessonContent Service (lessonContent.service.ts)", 3)
    add_paragraph(doc, "LessonContent Service chịu trách nhiệm quản lý nội dung chi tiết của từng bài giảng.")
    add_paragraph(doc, "Các chức năng chính:")
    add_bullet(doc, "Quản lý nội dung văn bản của bài giảng")
    add_bullet(doc, "Cập nhật nội dung học tập")
    add_bullet(doc, "Truy vấn nội dung theo bài giảng")
    add_paragraph(doc, "Service này cho phép mở rộng hệ thống với nhiều loại nội dung khác nhau trong tương lai.")
    add_paragraph(doc, "Service này giúp nhóm hiểu rõ hơn cách tách riêng nội dung học tập khỏi thông tin bài giảng.")

    add_heading(doc, "3.3.4.8 LessonMedia & Attachment Service", 3)
    add_paragraph(doc, "Nhóm service này được xây dựng để quản lý tài nguyên media và các file đính kèm trong bài giảng (lessonMedia.service.ts, media.service.ts, attachment.service.ts).")
    add_paragraph(doc, "Các chức năng chính:")
    add_bullet(doc, "Quản lý file media và tài nguyên đính kèm")
    add_bullet(doc, "Liên kết tài nguyên với bài giảng")
    add_bullet(doc, "Lưu trữ metadata của file")
    add_paragraph(doc, "Việc tách riêng các service này giúp hệ thống xử lý tài nguyên một cách nhất quán và hiệu quả.")
    add_paragraph(doc, "Service này giúp nhóm hiểu rõ hơn cách xử lý và tổ chức tài nguyên trong backend.")

    add_heading(doc, "3.3.4.9 LessonOrder & LessonStatus Service", 3)
    add_paragraph(doc, "Hai service này hỗ trợ việc quản lý thứ tự hiển thị và trạng thái bài học trong hệ thống (lessonOrder.service.ts, lessonStatus.service.ts).")
    add_paragraph(doc, "Các chức năng chính:")
    add_bullet(doc, "Quản lý thứ tự bài giảng")
    add_bullet(doc, "Theo dõi trạng thái hoàn thành bài học")
    add_bullet(doc, "Hỗ trợ frontend hiển thị tiến trình học tập")
    add_paragraph(doc, "Service này giúp nhóm hiểu rõ hơn cách hỗ trợ frontend hiển thị tiến trình học tập.")

    add_heading(doc, "3.3.4.10 Objectives, Preparation, Model & Build Service", 3)
    add_paragraph(doc, "Các service này hỗ trợ việc xây dựng nội dung học tập chi tiết cho từng bài giảng:")
    add_bullet(doc, "Objectives Service: Quản lý mục tiêu học tập")
    add_bullet(doc, "Preparation Service: Quản lý nội dung chuẩn bị bài học")
    add_bullet(doc, "Model Service: Quản lý mô hình hoặc nội dung lý thuyết")
    add_bullet(doc, "Build Service: Quản lý nội dung thực hành")
    add_paragraph(doc, "Nhóm service này giúp bài giảng có cấu trúc rõ ràng và logic.")
    add_paragraph(doc, "Service này giúp nhóm hiểu rõ hơn cách xây dựng bài giảng có cấu trúc logic.")

    add_heading(doc, "3.3.4.11 Quiz & Challenge Service", 3)
    add_paragraph(doc, "Quiz Service và Challenge Service hỗ trợ việc đánh giá và kiểm tra kiến thức người học (quiz.service.ts, challenge.service.ts).")
    add_paragraph(doc, "Các chức năng chính:")
    add_bullet(doc, "Quản lý câu hỏi trắc nghiệm")
    add_bullet(doc, "Quản lý thử thách học tập")
    add_bullet(doc, "Hỗ trợ đánh giá kết quả học tập")
    add_paragraph(doc, "Service này giúp nhóm hiểu rõ hơn cách triển khai chức năng đánh giá trong hệ thống học tập.")

    add_heading(doc, "3.3.4.12 Dashboard & Logs Service", 3)
    add_paragraph(doc, "Dashboard Service cung cấp dữ liệu tổng hợp phục vụ việc hiển thị thống kê cho hệ thống quản trị. Logs Service hỗ trợ ghi nhận và theo dõi các hoạt động trong hệ thống (dashboard.service.ts, logs.service.ts).")
    add_paragraph(doc, "Các chức năng chính:")
    add_bullet(doc, "Tổng hợp dữ liệu thống kê")
    add_bullet(doc, "Theo dõi hoạt động hệ thống")
    add_bullet(doc, "Hỗ trợ kiểm tra và xử lý lỗi")
    add_paragraph(doc, "Service này giúp nhóm hiểu rõ hơn cách thu thập và phân tích dữ liệu hệ thống.")

    add_heading(doc, "3.3.4.13 Mối quan hệ tổng thể giữa các service", 3)
    add_paragraph(doc, "Tất cả các service trong hệ thống backend được thiết kế để hoạt động độc lập nhưng liên kết chặt chẽ với nhau thông qua controller và cơ sở dữ liệu. Cách tổ chức này giúp backend đảm bảo tính mở rộng, ổn định và dễ bảo trì.")
    add_paragraph(doc, "Toàn bộ hệ thống service được chia thành ba nhóm chính gồm: nhóm quản lý người dùng và phân quyền, nhóm quản lý nội dung đào tạo và nhóm đánh giá – theo dõi học tập. Việc phân nhóm này giúp backend có cấu trúc rõ ràng, dễ phát triển và dễ bảo trì trong dài hạn.")

    add_heading(doc, "3.4 KIẾN TRÚC HỆ THỐNG FRONTEND", 1)
    add_heading(doc, "3.4.1 Mô hình tổ chức mã nguồn (Project Structure)", 2)
    add_paragraph(doc, "Dự án được xây dựng trên nền tảng thư viện ReactJS kết hợp với TypeScript, tuân thủ nghiêm ngặt nguyên tắc \"Separation of Concerns\" (Phân tách mối quan tâm). Mã nguồn được chia thành hai tầng chính: tầng hiển thị (Pages) và tầng xử lý/tái sử dụng (Components).")
    add_paragraph(doc, "Cấu trúc thư mục được quy hoạch theo tư duy phân tầng chức năng để quản lý độ phức tạp khi dự án mở rộng:")
    add_bullet(doc, "src/pages/: Đóng vai trò là các Container Components, chịu trách nhiệm xử lý logic nghiệp vụ, gọi API và điều phối dữ liệu cho từng màn hình cụ thể.")
    add_bullet(doc, "src/components/: Chứa các \"nguyên tử\" giao diện (Atoms) theo tư duy Atomic Design như Button, Card, Input. Các thành phần này hoàn toàn không chứa logic nghiệp vụ để tối đa hóa khả năng tái sử dụng.")
    add_bullet(doc, "src/services/: Tầng dịch vụ tập trung hóa mọi giao tiếp với Backend thông qua file api.ts, giúp tách biệt logic giao diện khỏi logic dữ liệu.")
    add_bullet(doc, "src/context/: Sử dụng React Context API để quản lý trạng thái toàn cục (Global State), đặc biệt là thông tin xác thực người dùng, giúp giải quyết vấn đề Prop Drilling.")

    add_heading(doc, "3.4.2 Công nghệ và Thư viện sử dụng", 2)
    add_paragraph(doc, "Core: React 18 (Functional Components & Hooks).")
    add_paragraph(doc, "Language: TypeScript (Đảm bảo tính chặt chẽ về kiểu dữ liệu cho Props và State).")
    add_paragraph(doc, "Styling: Tailwind CSS (Sử dụng utility-first class để xây dựng giao diện Dark Mode/Glassmorphism).")
    add_paragraph(doc, "Routing: React Router DOM (Điều hướng giữa các trang Dashboard, Courses, Lessons).")
    add_paragraph(doc, "Icons: Heroicons (Hệ thống icon đồng bộ).")
    add_paragraph(doc, "Lý do lựa chọn công nghệ (React + TypeScript + Tailwind CSS) là việc kết hợp bộ ba công nghệ này mang lại giải pháp toàn diện cho hệ thống quản trị:")
    add_paragraph(doc, "Về giao diện & trải nghiệm: ReactJS giúp tối ưu hóa hiệu năng thông qua cơ chế Virtual DOM và khả năng tái sử dụng mã nguồn (Component), trong khi Tailwind CSS đẩy nhanh tốc độ thiết kế giao diện hiện đại (Dark Mode, Glassmorphism) mà không tốn nhiều công sức tùy biến.")
    add_paragraph(doc, "Về độ tin cậy & bảo trì: TypeScript đóng vai trò \"xương sống\" bảo vệ hệ thống, giúp định nghĩa tường minh cấu trúc dữ liệu và phát hiện lỗi ngay trong quá trình viết code, đảm bảo tính chính xác cho các nghiệp vụ xử lý dữ liệu phức tạp của Admin.")

    add_heading(doc, "3.5 THIẾT KẾ GIAO DIỆN VÀ TRẢI NGHIỆM NGƯỜI DÙNG", 1)
    add_paragraph(doc, "Với mục tiêu xây dựng một trang quản trị không chỉ mạnh về chức năng mà còn đẹp về hình thức, dự án đã áp dụng các xu hướng thiết kế web hiện đại nhất năm 2024. Giao diện được xây dựng hoàn toàn bằng Tailwind CSS, cho phép tùy biến sâu (customization) từng chi tiết nhỏ.")

    add_heading(doc, "3.5.1 Phong cách thiết kế chủ đạo: Dark Mode & Glassmorphism", 2)
    add_paragraph(doc, "Dựa trên đặc thù là website về công nghệ (Robotics), giao diện Admin được thiết kế theo tông màu tối (Dark Theme) kết hợp với hiệu ứng kính mờ (Glassmorphism).")
    add_paragraph(doc, "Bảng màu (Color Palette):")
    add_bullet(doc, "Nền (Background): Sử dụng màu đen sâu hoặc xám than (bg-black hoặc bg-[#1a1a1a]) giúp giảm mỏi mắt khi Admin phải làm việc thời gian dài.")
    add_bullet(doc, "Điểm nhấn (Accent Colors): Sử dụng dải màu Gradient chuyển từ Tím sang Xanh dương (from-[#9c00e5] to-[#3c90ff]) hoặc Tím sang Đỏ (to-[#ff7c7c]). Dải màu này xuất hiện xuyên suốt trên các nút bấm (Buttons), thanh tiêu đề và các biểu đồ, tạo nên bộ nhận diện thương hiệu mạnh mẽ.")
    add_bullet(doc, "Văn bản (Typography): Sử dụng màu trắng (text-white) cho tiêu đề và xám nhạt (text-gray-300, text-gray-400) cho nội dung phụ để tạo độ tương phản tốt.")
    add_paragraph(doc, "Hiệu ứng Kính mờ (Glassmorphism):")
    add_bullet(doc, "Thay vì sử dụng các khối màu đặc (Solid colors), các thành phần như Card thống kê, Modal, Sidebar sử dụng lớp nền bán trong suốt.")
    add_bullet(doc, "Kỹ thuật: Sử dụng class bg-white/5 (trắng đục 5%) hoặc bg-black/20 kết hợp với backdrop-blur-xl (làm mờ hậu cảnh).")
    add_bullet(doc, "Đường viền: Các khối được bao quanh bởi đường viền siêu mảnh border border-white/10, tạo cảm giác nổi khối 3D tinh tế.")

    add_heading(doc, "3.5.2 Hiệu ứng chuyển động và Vi tương tác (Micro-interactions)", 2)
    add_paragraph(doc, "Trải nghiệm người dùng được nâng cao thông qua các chuyển động mượt mà, giúp giao diện trở nên \"sống động\" và phản hồi tức thì với thao tác của người dùng.")
    add_paragraph(doc, "Animation tùy chỉnh (Custom Keyframes):")
    add_bullet(doc, "Trong các file như AdminDashboardPage.tsx hay AdminCoursesPage.tsx, mã nguồn định nghĩa trực tiếp các keyframes animation:")
    add_bullet(doc, "Ứng dụng: Khi tải trang, các bảng dữ liệu và thẻ thống kê không hiện ra đột ngột mà trượt nhẹ từ dưới lên (animate-slide-in), tạo cảm giác mượt mà.")
    add_paragraph(doc, "Hiệu ứng Hover (Rê chuột):")
    add_bullet(doc, "Nút bấm: Khi di chuột vào nút, nút sẽ đổi màu nền (hover:bg-white/10) hoặc đổ bóng phát sáng (shadow-lg shadow-[#9c00e5]/30), báo hiệu cho người dùng biết đây là phần tử có thể tương tác.")
    add_paragraph(doc, "Scrollbar tùy chỉnh:")
    add_bullet(doc, "Thanh cuộn mặc định của trình duyệt được thay thế bằng thanh cuộn nhỏ gọn, có màu tím thương hiệu (custom-scrollbar), đồng bộ với tổng thể giao diện.")

    add_heading(doc, "3.5.3 Thiết kế bố cục và điều hướng", 2)
    add_paragraph(doc, "Hệ thống sử dụng bố cục Dashboard Layout kinh điển nhưng được tối ưu hóa bằng Flexbox và Grid System.")
    add_paragraph(doc, "Cấu trúc lưới (Grid System):")
    add_bullet(doc, "Tại trang AdminDashboardPage.tsx, sử dụng grid-cols-1 md:grid-cols-2 lg:grid-cols-4. Điều này giúp giao diện tự động thích ứng (Responsive): hiển thị 4 cột trên máy tính, 2 cột trên máy tính bảng và 1 cột trên điện thoại.")
    add_paragraph(doc, "Điều hướng theo Tab (Tabbed Interface):")
    add_bullet(doc, "Tại trang chi tiết bài giảng (AdminLessonPage.tsx), thay vì bắt người dùng cuộn một trang rất dài, nội dung được chia thành các Tab ngang: Mục tiêu/ Video thành phẩm/ Vật liệu/ Slide ráp ráp/ Lý thuyết/ Thử thách/ Tổng kết.")
    add_bullet(doc, "Logic: Sử dụng State activeTab để render có điều kiện phần nội dung tương ứng, giúp giao diện gọn gàng và tập trung.")

    add_heading(doc, "3.5.4 Cơ chế phản hồi và trạng thái hệ thống", 2)
    add_paragraph(doc, "Giao diện luôn thông báo rõ ràng cho người dùng về trạng thái hiện tại của hệ thống, tránh việc người dùng hoang mang không biết thao tác đã thành công hay chưa.")
    add_paragraph(doc, "Trạng thái Tải (Loading State):")
    add_bullet(doc, "Trong AdminCoursesPage.tsx hay ManageTeachersPage.tsx, khi dữ liệu đang được lấy từ API, hệ thống hiển thị hiệu ứng xoay (Spinner) hoặc Skeleton Loading.")
    add_bullet(doc, "Trên các nút bấm như \"Lưu\" hay \"Xóa\", khi đang xử lý (isLoading = true), nút sẽ bị vô hiệu hóa (disabled), giảm độ mờ (opacity-50) và đổi nhãn thành \"Đang lưu...\" để ngăn người dùng click nhiều lần (Double-submit prevention).")
    add_paragraph(doc, "Thông báo nổi (Toast Notifications):")
    add_bullet(doc, "Được cài đặt trong AssignCoursesPage.tsx. Khi Admin phân công thành công hoặc gặp lỗi, một thẻ thông báo nhỏ sẽ trượt ra từ góc màn hình (xanh lá cho thành công, đỏ cho lỗi) và tự động biến mất sau 3 giây.")
    add_paragraph(doc, "Modal xác nhận (Confirmation Dialogs):")
    add_bullet(doc, "Các thao tác quan trọng như Xóa khóa học hay Phân công giáo viên đều được thực hiện qua các cửa sổ bật lên (AssignmentModal, CourseModal). Nền phía sau được làm tối (bg-black/80), buộc người dùng phải tập trung vào tác vụ hiện tại trước khi quay lại màn hình chính.")

    add_heading(doc, "3.5.5 Vai trò hỗ trợ ra quyết định quản trị", 2)
    add_paragraph(doc, "Ngoài yếu tố thẩm mỹ, giao diện Dashboard được thiết kế để giải quyết bài toán \"Quản trị dựa trên dữ liệu\" (Data-driven Management), giúp Ban lãnh đạo đưa ra quyết định chính xác thông qua các thành phần trực quan:")
    add_paragraph(doc, "Đánh giá năng lực đào tạo tức thì:")
    add_bullet(doc, "Thông qua các Thẻ thống kê (Stats Cards) hiển thị số lượng Giáo viên và Khóa học theo thời gian thực, nhà quản lý có thể đánh giá ngay lập tức quy mô hiện tại của trung tâm. Nếu tỉ lệ Khóa học/Giáo viên quá cao, hệ thống ngầm cảnh báo cần tuyển dụng thêm nhân sự để đảm bảo chất lượng đào tạo.")
    add_paragraph(doc, "Tối ưu hóa điều phối lịch trình:")
    add_bullet(doc, "Widget Lịch biểu (Calendar) không chỉ hiển thị ngày tháng mà còn trực quan hóa mật độ lớp học bằng các điểm đánh dấu (Dots). Nhìn vào lịch, Admin có thể quyết định thời điểm thích hợp để mở lớp mới tránh các ngày cao điểm, hoặc điều chuyển lịch dạy để cân bằng tải công việc cho đội ngũ giáo viên.")
    add_paragraph(doc, "Kiểm soát rủi ro vận hành:")
    add_bullet(doc, "Khu vực \"Hoạt động gần đây\" (Recent Activities) đóng vai trò như một nhật ký kiểm toán (Audit Log). Nhà quản lý có thể giám sát ai vừa được phân công vào khóa học nào theo thời gian thực. Điều này hỗ trợ ra quyết định can thiệp ngay lập tức nếu phát hiện sự cố phân quyền sai hoặc thao tác trái phép, đảm bảo tính an toàn cho hệ thống.")

    add_heading(doc, "3.6 THIẾT KẾ DỮ LIỆU VÀ TƯƠNG TÁC API", 1)
    add_paragraph(doc, "Để đảm bảo tính nhất quán và giảm thiểu lỗi trong quá trình chạy (Runtime Errors), hệ thống Frontend sử dụng TypeScript để định nghĩa chặt chẽ các kiểu dữ liệu (Interfaces) và tuân thủ chuẩn RESTful API trong giao tiếp với Server.")

    add_heading(doc, "3.6.1 Mô hình Dữ liệu", 2)
    add_paragraph(doc, "Toàn bộ các đối tượng dữ liệu trả về từ API đều được mô hình hóa thành các interface. Điều này giúp IDE (VS Code) gợi ý code thông minh và báo lỗi ngay khi lập trình viên truy cập sai thuộc tính.")
    add_bullet(doc, "Mô hình Giáo viên (Teacher Interface): Được sử dụng trong ManageTeachersPage.tsx để hiển thị danh sách nhân sự.")
    add_bullet(doc, "Mô hình Khóa học và Bài giảng (Course & Lesson Model): Dữ liệu khóa học có cấu trúc phân cấp: Một khóa học chứa nhiều bài giảng, mỗi bài giảng chứa nhiều thành phần (Slide, Quiz, Video).")
    add_bullet(doc, "Mô hình Dữ liệu Form (Form Data Interface): Được sử dụng trong CreateTeacherPage.tsx để quản lý dữ liệu đầu vào trước khi gửi đi.")

    add_heading(doc, "3.6.2 Cơ chế Tương tác API", 2)
    add_paragraph(doc, "Hệ thống sử dụng cơ chế HTTP Request tiêu chuẩn (GET, POST, PUT, DELETE) để giao tiếp với Backend thông qua fetch API kết hợp với async/await để xử lý bất đồng bộ.")
    add_bullet(doc, "Phương thức GET (Lấy dữ liệu): Sử dụng để tải danh sách giáo viên hoặc khóa học khi trang vừa được tải (Component Mount).")
    add_bullet(doc, "Phương thức POST (Gửi dữ liệu): Sử dụng trong chức năng Phân công giảng dạy (AssignCoursesPage.tsx). Dữ liệu được đóng gói thành JSON body trước khi gửi.")

    add_heading(doc, "3.6.3 Quản lý trạng thái và luồng dữ liệu", 2)
    add_paragraph(doc, "Dự án áp dụng mô hình Local State Management bằng React Hooks để quản lý vòng đời của dữ liệu trên giao diện.")
    add_bullet(doc, "Khởi tạo State: Mỗi trang quản lý các biến trạng thái riêng biệt cho dữ liệu (data), trạng thái tải (loading) và lỗi (error).")
    add_bullet(doc, "Đồng bộ hóa với useEffect: Sử dụng useEffect để kích hoạt việc gọi API ngay khi component được render lần đầu tiên.")
    add_bullet(doc, "Cập nhật UI thời gian thực (Optimistic UI Update): Trong chức năng Xóa (handleDelete), thay vì tải lại toàn bộ trang, hệ thống thực hiện lọc bỏ phần tử khỏi State ngay lập tức để giao diện phản hồi nhanh hơn. Thay vì tải lại toàn bộ trang sau khi xóa, hệ thống sử dụng phương pháp cập nhật giao diện lạc quan (Optimistic UI). Ngay khi nhận phản hồi thành công từ Server, Client sẽ chủ động lọc bỏ giáo viên đó khỏi mảng teachers trong State, giúp giao diện phản hồi tức thì.")
    add_paragraph(doc, "Hệ thống áp dụng kiến trúc quản lý trạng thái đa tầng nhằm tối ưu hóa hiệu năng và tính dễ đoán của dữ liệu:")
    add_bullet(doc, "Luồng dữ liệu một chiều (Unidirectional Data Flow): Tuân thủ nghiêm ngặt nguyên tắc Data Down, Action Up. Dữ liệu từ Container Component truyền xuống Component con qua Props, trong khi các tương tác từ con được gửi ngược lại cha qua Callback functions.")
    add_bullet(doc, "Xử lý bất đồng bộ (Async State Management): Mọi yêu cầu mạng đều được quản lý qua bộ 3 trạng thái: Loading (hiển thị Skeleton UI), Success (cập nhật dữ liệu), và Error (hiển thị thông báo lỗi thân thiện).")
    add_bullet(doc, "Ngăn chặn Race Conditions: Sử dụng Cleanup Function trong useEffect kết hợp AbortController để hủy bỏ các yêu cầu API cũ khi người dùng thao tác chuyển bài học liên tục, đảm bảo tính chính xác của dữ liệu hiển thị.")

    add_heading(doc, "3.7 PHÂN TÍCH CHI TIẾT CHỨC NĂNG VÀ THIẾT KẾ COMPONENT", 1)
    add_paragraph(doc, "Hệ thống Admin được xây dựng dựa trên kiến trúc Component-Based, trong đó mỗi phân hệ chức năng (Module) được cấu thành từ một Trang chính (Container Page) và nhiều Thành phần con (Presentational Components) đảm nhiệm các tác vụ cụ thể.")

    add_heading(doc, "3.7.1 Phân hệ Quản lý Khóa học (Course Management Module)", 2)
    add_paragraph(doc, "Đây là phân hệ nền tảng, cho phép Admin thiết lập và quản lý danh mục sản phẩm giáo dục của trung tâm.")
    add_heading(doc, "3.7.1.1 Trang điều phối: AdminCoursesPage.tsx", 3)
    add_bullet(doc, "Chức năng: Hiển thị toàn bộ danh sách khóa học dưới dạng lưới (Grid) hoặc danh sách (List).")
    add_bullet(doc, "Logic xử lý Phân trang (Client-side Pagination): Thay vì tải lại trang, hệ thống tải toàn bộ danh sách về và chia nhỏ mảng dữ liệu (array.slice) dựa trên biến currentPage và itemsPerPage. Điều này giúp trải nghiệm chuyển trang diễn ra tức thì.")
    add_bullet(doc, "Logic Tìm kiếm & Lọc: Sử dụng hook useEffect để lắng nghe thay đổi từ ô input tìm kiếm, thực hiện lọc mảng (filter) theo tên khóa học hoặc trạng thái (Archive/Publish) theo thời gian thực.")
    add_paragraph(doc, "Khó khăn và giải pháp xử lý kỹ thuật (Điều chỉnh theo code thực tế):")
    add_bullet(doc, "a) Xung đột trạng thái giữa Tìm kiếm và Phân trang")
    add_paragraph(doc, "Vấn đề: Khi người dùng đang ở trang xa và thực hiện tìm kiếm, nếu kết quả trả về ít hơn 5 trang, giao diện sẽ bị trắng do chỉ số currentPage vẫn giữ giá trị cũ trong khi dữ liệu mới không đủ số trang đó.")
    add_paragraph(doc, "Giải pháp trong code: Xử lý việc này ngay trong Hook Lọc dữ liệu (useEffect). Mỗi khi biến searchTerm hoặc filterCode thay đổi, hệ thống không chỉ tính toán lại danh sách filteredCourses mà còn ép buộc setCurrentPage(1) ngay lập tức. Cách làm này đảm bảo tính nhất quán dữ liệu trong một lần render duy nhất.")
    add_bullet(doc, "b) Đồng bộ dữ liệu")
    add_paragraph(doc, "Mô tả: Hệ thống Backend chia dữ liệu khóa học thành các endpoint riêng biệt dựa trên chương trình học (ví dụ: programs/1 cho Essential và programs/2 cho Prime). Việc này gây khó khăn khi Frontend cần hiển thị một danh sách tổng hợp gồm tất cả các khóa học để Admin quản lý chung.")
    add_paragraph(doc, "Giải pháp: Sử dụng kỹ thuật Data Aggregation (Tổng hợp dữ liệu) tại phía Client. Thay vì gọi API tuần tự (cách làm truyền thống gây chậm), sử dụng Promise.all để kích hoạt các request song song. Sau khi nhận phản hồi, sử dụng toán tử Spread (...) để gộp các mảng con thành một mảng duy nhất và tiến hành chuẩn hóa (Mapping) về cùng một cấu trúc Interface.")
    add_bullet(doc, "c) Trải nghiệm người dùng khi tải dữ liệu")
    add_paragraph(doc, "Mô tả: Khi thực hiện gộp dữ liệu từ nhiều nguồn, thời gian phản hồi có thể lâu hơn bình thường. Nếu để màn hình trắng, người dùng sẽ tưởng hệ thống bị treo.")
    add_paragraph(doc, "Giải pháp: Thiết lập biến trạng thái loading. Trong lúc Promise.all đang chạy, giao diện sẽ hiển thị trạng thái \"Đang tải dữ liệu...\" hoặc Skeleton Loading. Ngay sau khi quá trình gộp dữ liệu hoàn tất (finally), loading được set về false để hiển thị bảng dữ liệu.")

    add_heading(doc, "3.7.1.2 Component vệ tinh", 3)
    add_bullet(doc, "CreateCourseModal.tsx: Form chuyên biệt để khởi tạo khóa học. Component này tách biệt logic validate dữ liệu đầu vào (Tên khóa học không được để trống, Mô tả phải có độ dài tối thiểu) trước khi gửi request POST về Server.")
    add_bullet(doc, "CourseModal.tsx (Edit Mode): Modal này nhận props là object course hiện tại. Nó sử dụng kỹ thuật Controlled Component để điền sẵn dữ liệu vào các ô input, cho phép Admin sửa đổi thông tin hoặc cập nhật trạng thái hiển thị.")
    add_bullet(doc, "CoursePermissionSelector.tsx: Một component tái sử dụng giúp Admin phân quyền truy cập cho khóa học (Ví dụ: \"draft\" | \"published\" | \"archived\"). Việc tách riêng logic này giúp dễ dàng nhúng vào bất kỳ form nào cần chọn quyền hạn.")

    add_heading(doc, "3.7.2 Phân hệ hệ thống quản trị nội dung bài giảng", 2)
    add_paragraph(doc, "Đây là phân hệ phức tạp nhất về mặt kỹ thuật, biến website thành một công cụ soạn thảo nội dung đa phương tiện mạnh mẽ.")
    add_heading(doc, "3.7.2.1 Trang điều phối: AdminLessonPage.tsx", 3)
    add_bullet(doc, "Vai trò Container: Trang này không hiển thị trực tiếp nội dung mà đóng vai trò là một \"bộ khung\" (Hub). Nó quản lý một biến trạng thái activeTab để điều hướng người dùng giữa các module nội dung khác nhau (Nội dung, Slide, Video, Quiz...).")
    add_bullet(doc, "Quản lý State tập trung: Dữ liệu bài giảng được gọi API một lần tại đây và truyền xuống các component con thông qua props, đảm bảo tính đồng nhất dữ liệu.")

    add_heading(doc, "3.7.2.2 Các Module Component chi tiết (trong thư mục admin/lesson/)", 3)
    add_paragraph(doc, "Module Đa phương tiện (LessonSlides.tsx & LessonVideo.tsx):")
    add_bullet(doc, "LessonSlides.tsx: Cho phép upload hàng loạt ảnh slide. Logic xử lý mảng cho phép Admin sắp xếp lại thứ tự (re-order) hoặc xóa từng slide cụ thể mà không ảnh hưởng đến các slide khác. Module này hỗ trợ cho việc quản lý slide bài giảng cho bài học đang trỏ tới.")
    add_bullet(doc, "LessonProductVideo.tsx: Tương tự như LessonSlides, module này cho phép upload video (nhưng khác với LessonSlide chỉ có thể up 1 video giới thiệu bài giảng) giúp quản lý tài nguyên video rõ ràng.")
    add_paragraph(doc, "Module Nội dung & Mục tiêu (LessonContent.tsx & LessonObjectives.tsx):")
    add_bullet(doc, "LessonObjectives.tsx: Quản lý danh sách các gạch đầu dòng \"Mục tiêu bài học\". Logic sử dụng mảng dynamic, cho phép thêm/xóa dòng mục tiêu linh hoạt bằng các nút + và x.")
    add_paragraph(doc, "Module Đánh giá & Tương tác (LessonQuiz.tsx & LessonChallenge.tsx):")
    add_bullet(doc, "LessonQuiz.tsx: Hệ thống soạn thảo câu hỏi trắc nghiệm phức tạp. Cấu trúc dữ liệu: Mỗi câu hỏi là một object chứa question_text, mảng options (các phương án) và correct_index (chỉ số đáp án đúng). Logic: Admin có thể thêm vô số câu hỏi. Giao diện cho phép tích chọn (Radio button) để xác định đáp án đúng ngay trên màn hình soạn thảo.")
    add_bullet(doc, "LessonChallenge.tsx: Quản lý các bài tập thử thách nâng cao, khuyến khích học viên thực hành sau giờ học.")
    add_paragraph(doc, "Tóm tắt kỹ thuật: Phân hệ này áp dụng triệt để kiến trúc Component Composition (Tổ hợp Component), tách biệt các logic nghiệp vụ phức tạp (như xử lý mảng Slide, cấu trúc JSON lồng nhau của Quiz) thành các module độc lập để dễ bảo trì. Luồng dữ liệu tuân thủ nguyên tắc One-way Data Flow (Dữ liệu một chiều): Container AdminLessonPage chịu trách nhiệm gọi API và quản lý State tập trung, sau đó truyền xuống các Component con thông qua Props, đảm bảo tính nhất quán và giảm thiểu việc render thừa trong quá trình thao tác dữ liệu.")

    add_heading(doc, "3.7.3 Phân hệ quản lý nhân sự và phân công", 2)
    add_paragraph(doc, "Phân hệ này giải quyết bài toán nghiệp vụ cốt lõi: Phân phối nguồn lực giảng dạy.")
    add_paragraph(doc, "Quản lý Giáo viên (ManageTeachersPage.tsx & CreateTeacherPage.tsx):")
    add_bullet(doc, "Danh sách nhân sự: Hiển thị bảng thông tin giáo viên với các cột: Avatar, Tên đăng nhập, Email, Họ tên.")
    add_bullet(doc, "Chức năng Reset Password: Tích hợp logic cho phép Admin đặt lại mật khẩu cho giáo viên ngay tại danh sách, giúp xử lý nhanh các trường hợp quên mật khẩu.")
    add_bullet(doc, "Form thêm mới (CreateTeacherPage): Sử dụng các input type password và email kết hợp với validate HTML5 để đảm bảo tính chính xác của dữ liệu tài khoản.")
    add_paragraph(doc, "Hệ thống Phân công (AssignCoursesPage.tsx):")
    add_bullet(doc, "Mô hình quan hệ: Xử lý mối quan hệ \"Nhiều - Nhiều\" (Many-to-Many) giữa bảng Users (Giáo viên) và bảng Courses.")
    add_bullet(doc, "Component AssignmentModal.tsx: Đây là trái tim của phân hệ này.")
    add_bullet(doc, "Dropdown thông minh: Load danh sách toàn bộ Giáo viên và Khóa học vào 2 menu thả xuống.")
    add_bullet(doc, "Validation Logic: Khi Admin chọn 1 Giáo viên và 1 Khóa học, hệ thống sẽ kiểm tra xem cặp đôi này đã tồn tại trong cơ sở dữ liệu chưa để ngăn chặn việc phân công trùng lặp (Duplicate Entry).")
    add_bullet(doc, "Quy trình Duyệt (Approval Workflow): Trang danh sách phân công có các tab trạng thái (Active/Pending). Các yêu cầu phân công mới sẽ nằm ở trạng thái chờ, Admin cần xác nhận để kích hoạt quyền truy cập cho giáo viên.")
    add_paragraph(doc, "Tóm tắt kỹ thuật & Bài học kinh nghiệm: Thông qua việc phát triển phân hệ này, nhóm nghiên cứu đã giải quyết thành công bài toán xử lý Quan hệ Nhiều - Nhiều (Many-to-Many) giữa thực thể Giáo viên và Khóa học. Điểm nhấn kỹ thuật nằm ở cơ chế Ngăn chặn trùng lặp dữ liệu (Duplicate Prevention) ngay tại phía Client:")
    add_paragraph(doc, "Logic xử lý: Trong AssignmentModal, hệ thống sử dụng thuật toán lọc mảng (filter kết hợp includes) để so sánh danh sách khóa học đang chọn với danh sách phân công hiện có trong lịch sử.")
    add_paragraph(doc, "Kết quả: Các khóa học đã được gán cho giáo viên đó sẽ tự động bị vô hiệu hóa (Disabled) trên giao diện chọn, giúp ngăn chặn triệt để lỗi vi phạm ràng buộc duy nhất (Unique Constraint) trước khi gửi dữ liệu về Server, đảm bảo tính toàn vẹn của cơ sở dữ liệu.")

    add_heading(doc, "3.7.4 Phân hệ Dashboard Tổng quan (Analytics Dashboard)", 2)
    add_bullet(doc, "Trang hiển thị: AdminDashboardPage.tsx")
    add_bullet(doc, "Trực quan hóa dữ liệu: Tổng hợp các chỉ số quan trọng (KPIs) như Tổng số giáo viên, Tổng số khóa học đang hoạt động.")
    add_bullet(doc, "Nhật ký hoạt động (Activity Logs): Component này hiển thị dòng thời gian (Timeline) các thao tác gần nhất trên hệ thống (Ví dụ: \"Giáo viên A vừa cập nhật bài giảng B\"). Điều này giúp Admin giám sát chặt chẽ mọi thay đổi dữ liệu.")

    add_heading(doc, "3.7.5 Phân hệ Xác thực và Bảo mật (Authentication Module)", 2)
    add_paragraph(doc, "Phân hệ này được thiết kế như một hệ thống kiểm soát truy cập toàn diện, sử dụng kiến trúc tập trung dựa trên AuthContext.")
    add_bullet(doc, "Quản lý trạng thái: Lưu trữ các thông tin cốt lõi gồm đối tượng người dùng, trạng thái isAuthenticated và trạng thái isLoading để ngăn chặn hiện tượng nháy trang khi chưa khởi tạo xong phiên làm việc.")
    add_bullet(doc, "Đồng bộ phiên (Hydration): Khi người dùng tải lại trang (F5), hệ thống tự động truy xuất accessToken từ LocalStorage để khôi phục trạng thái đăng nhập, đảm bảo trải nghiệm không bị gián đoạn.")
    add_bullet(doc, "Bảo vệ luồng truy cập (Route Guarding): Sử dụng cơ chế Private Route Wrapper để bọc các trang dành riêng cho giáo viên. Nếu người dùng chưa xác thực, hệ thống sẽ cưỡng chế điều hướng về trang đăng nhập.")

    add_heading(doc, "3.7.6 Phân hệ Cổng thông tin Giáo viên (Teacher Portal)", 2)
    add_paragraph(doc, "Đảm nhiệm vai trò điều hướng và giúp giáo viên tiếp cận tài liệu giảng dạy thông qua lộ trình 3 bước: Trang chủ > Chọn chương trình > Danh sách khóa học.")
    add_bullet(doc, "Thiết kế đáp ứng (Responsive Grid): Sử dụng CSS Grid với hàm repeat (auto-fill, minmax (300px, 1fr)) giúp giao diện tự động thích ứng với nhiều kích thước màn hình từ máy chiếu đến máy tính bảng.")
    add_bullet(doc, "Lọc dữ liệu phía Client: Tích hợp tính năng tìm kiếm và lọc theo cấp độ ngay tại trình duyệt thông qua useMemo, giúp loại bỏ độ trễ mạng và mang lại phản hồi tức thì cho người dùng.")

    add_heading(doc, "3.7.7 Trình phát bài giảng tương tác (Interactive Lesson Player)", 2)
    add_paragraph(doc, "Đây là tính năng cốt lõi, thay thế các công cụ trình chiếu truyền thống bằng một môi trường thực thi bài giảng trực tiếp trên trình duyệt.")
    add_bullet(doc, "Kiến trúc chuyển đổi nội dung: Áp dụng mô hình StageRenderer để hiển thị nội dung dựa trên 8 bước sư phạm chuẩn (Mục tiêu, Tổng quan, Lắp ráp PDF, Video, Quiz...) mà không cần tải lại trang.")
    add_bullet(doc, "Tối ưu hóa trình chiếu Slide: Sử dụng kỹ thuật Smart Pre-fetching (tải trước ảnh slide tiếp theo vào bộ nhớ đệm) để đảm bảo độ trễ bằng không khi giáo viên chuyển trang.")
    add_bullet(doc, "Quản lý Video thông minh: Trình phát video tùy chỉnh có khả năng ghi nhớ mốc thời gian (savedVideoTime) khi người dùng chuyển đổi giữa các tab nội dung, cho phép tiếp tục xem video tại đúng vị trí cũ khi quay lại.")
    add_heading(doc, "3.8.1 Thiết kế Bảo mật Tầng Dữ liệu với Row Level Security (RLS)", 2)
    add_paragraph(doc, "Thay vì chỉ dựa vào phân quyền ở tầng ứng dụng (Application Layer), hệ thống áp dụng cơ chế Row Level Security (RLS) của Supabase để chặn các rủi ro bảo mật từ gốc (Database Layer).")
    add_bullet(doc, "Kiến trúc xử lý: Mỗi request từ Client gửi lên Supabase đều kèm theo một JWT Token. Tại tầng PostgreSQL, các chính sách (Policies) sẽ giải mã token này để lấy auth.uid() và tiến hành đánh giá điều kiện trước khi cho phép đọc/ghi dữ liệu.")
    add_bullet(doc, "Logic phân quyền Học sinh: Bảng lessons và courses được gắn policy kiểm tra xem auth.uid() của học sinh có tồn tại trong bảng enrollments đối với khóa học tương ứng hay không. Nếu không, CSDL sẽ trả về mảng rỗng ngay lập tức, ngăn chặn hoàn toàn việc học sinh truy cập trái phép khóa học chưa đăng ký qua API.")
    add_bullet(doc, "Logic phân quyền Giáo viên: Áp dụng policy đối chiếu auth.uid() với cột teacher_id trong bảng assignments. Đảm bảo giáo viên chỉ có quyền truy cập và chấm điểm những lớp mình được phân công.")

    add_heading(doc, "3.8.2 Thiết kế Kiến trúc Đồng bộ Hóa Thời gian thực (Real-time Sync)", 2)
    add_paragraph(doc, "Bài toán đặt ra là làm sao giáo viên nhận được thông báo ngay lập tức khi được admin phân công lớp mới mà không cần phải thực hiện thao tác F5 (tải lại trang) hay hệ thống phải gọi API liên tục (Polling).")
    add_bullet(doc, "Giao thức sử dụng: Sử dụng WebSockets thông qua hệ thống Realtime của Supabase, lắng nghe trực tiếp luồng thay đổi dữ liệu (Replication Stream) của PostgreSQL.")
    add_bullet(doc, "Logic xử lý tại Frontend: Tại AuthContext hoặc các Hook quản lý trạng thái, một Channel được khởi tạo để lắng nghe sự kiện INSERT trên bảng assignments. Dữ liệu trả về sẽ được lọc (filter) tại Client: nếu teacher_id khớp với người dùng hiện tại, hệ thống sẽ kích hoạt một hàm Toast Notification (thông báo nổi) và tự động gọi lại hàm fetch để cập nhật danh sách khóa học, mang lại trải nghiệm liền mạch.")

    add_heading(doc, "3.8.3 Kỹ thuật Tối ưu Hiệu năng (Data Aggregation & N+1 Query)", 2)
    add_paragraph(doc, "Trong kiến trúc cũ, để tải toàn bộ nội dung của một bài học (gồm thông tin chung, mục tiêu, chuẩn bị, danh sách slide, video, quiz, challenge), Frontend phải thực hiện đồng thời nhiều request API độc lập, gây ra bài toán N+1 Query và làm tăng độ trễ (Latency).")
    add_bullet(doc, "Giải pháp Aggregation: Chuyển dịch tác vụ ghép nối dữ liệu (Data Joining) từ tầng Client/Node.js xuống thẳng tầng Cơ sở dữ liệu.")
    add_bullet(doc, "Triển khai RPC Function: Viết một hàm PostgreSQL (Stored Procedure/RPC) sử dụng các hàm JSON tích hợp sẵn như jsonb_build_object và json_agg. Hàm này thực hiện JOIN các bảng liên quan và đóng gói toàn bộ nội dung thành một JSON payload duy nhất trả về cho Client.")
    add_bullet(doc, "Đánh giá hiệu năng: Giải pháp này giảm số lượng request HTTP từ 6 xuống còn 1, giảm băng thông mạng và cắt giảm thời gian xử lý API xuống dưới 100ms, giúp trải nghiệm chuyển bài học của người dùng diễn ra tức thì.")

    add_heading(doc, "3.8.4 Kiến trúc tái sử dụng cho Cổng Tự học (Student Portal)", 2)
    add_paragraph(doc, "Cổng tự học dành cho học sinh yêu cầu hiển thị nội dung bài học giống như giao diện của giáo viên nhưng không được phép có các tính năng sửa, xóa hay quản lý.")
    add_bullet(doc, "Thiết kế Component đa hình (Polymorphic Components): Thay vì code lại một trang hoàn toàn mới, hệ thống tái sử dụng toàn bộ các component trình chiếu bài giảng (LessonContent, LessonVideo, LessonQuiz) nhưng thiết kế thêm một biến Prop: role=\"student\".")
    add_bullet(doc, "Render có điều kiện: Khi role=\"student\", các thành phần UI quản trị (như nút Edit, Delete) sẽ bị ẩn đi. Tại component Challenge, thay vì hiển thị danh sách bài nộp của học sinh (dành cho giáo viên), hệ thống sẽ render giao diện Nộp bài (Drag & Drop) dành riêng cho học sinh.")
    add_bullet(doc, "Theo dõi tiến độ (Progress Tracking): Tích hợp luồng ghi nhận dữ liệu vào bảng lesson_progress. Khi học sinh xem xong video hoặc nộp bài, Frontend sẽ trigger API cập nhật trạng thái (status: 'completed', score: ...), từ đó tính toán phần trăm hoàn thành khóa học.")

    add_heading(doc, "3.8.5 Thiết kế Luồng tương tác Nộp bài tệp đính kèm (.llsp3)", 2)
    add_paragraph(doc, "Để kết nối môi trường học tập lý thuyết với thực hành, hệ thống cho phép nộp file dự án lập trình từ phần mềm Lego SPIKE (.llsp3).")
    add_bullet(doc, "Xử lý Drag & Drop: Frontend xây dựng một vùng thả file (Dropzone) với các sự kiện onDragOver, onDrop. File tải lên được kiểm tra validation nghiêm ngặt về định dạng (.llsp3, .png, .jpg) và dung lượng (giới hạn 10MB) trước khi được xử lý.")
    add_bullet(doc, "Quản lý lưu trữ Storage: File được đẩy lên Supabase Storage thông qua API mã hóa Multipart. Hệ thống tạo đường dẫn thư mục theo định dạng student_id/lesson_id/filename để tránh xung đột tên file.")
    add_bullet(doc, "Ghi nhận tiến độ: Sau khi upload thành công, public URL của file sẽ được lưu vào thuộc tính submitted_file_url trong bảng lesson_progress, đóng vai trò như cầu nối để giáo viên có thể truy xuất và tải bài làm về chấm điểm.")

    add_heading(doc, "3.8.6 Kiến trúc Trợ lý AI Phân tích hình ảnh (AI Vision Tutor)", 2)
    add_paragraph(doc, "Nhằm giúp trẻ em tự giải quyết lỗi lập trình một cách độc lập, nền tảng tích hợp AI có khả năng thị giác (Vision AI) thông qua mô hình Gemini.")
    add_bullet(doc, "Luồng dữ liệu (Data Flow): Tại mục thử thách, học sinh nhấp vào tính năng \"Hỏi AI Trợ giảng\". Hệ thống cung cấp công cụ tải lên ảnh chụp màn hình khối lệnh bị lỗi. Ảnh được mã hóa sang dạng Base64 và đính kèm vào luồng chat.")
    add_bullet(doc, "Xử lý Backend AI: API Backend nhận ảnh và tin nhắn, sau đó ghép nối với một System Prompt được thiết kế chuyên biệt (Ví dụ: \"Đóng vai một gia sư hài hước, giải thích lỗi logic trong khối lệnh Lego...\"). Request được gửi đến Gemini API.")
    add_bullet(doc, "Phản hồi Stream: Thay vì đợi AI xử lý xong toàn bộ mới hiển thị, Backend sử dụng cơ chế Server-Sent Events (SSE) để trả về từng đoạn văn bản nhỏ (Streaming). Frontend nhận dữ liệu và tạo hiệu ứng gõ chữ (Typewriter effect) trực tiếp trên giao diện chat, mang lại cảm giác trò chuyện thực tế.")

    add_heading(doc, "3.8.7 Kỹ thuật Gamification (Hiệu ứng khen thưởng trực quan)", 2)
    add_paragraph(doc, "Gamification đóng vai trò quan trọng trong EdTech nhằm duy trì hứng thú và động lực của học sinh. Nền tảng ứng dụng điều này qua các hiệu ứng phần thưởng (Rewards).")
    add_bullet(doc, "Kiến trúc tích hợp: Sử dụng thư viện canvas-confetti kết hợp với các hoạt ảnh GSAP để tạo hiệu ứng pháo hoa và bóng bay.")
    add_bullet(doc, "Luồng thực thi Non-blocking: Để không làm gián đoạn trải nghiệm người dùng, hiệu ứng được kích hoạt (trigger) độc lập thông qua Callback Function ngay khi API nộp bài (submit) trả về mã 200 OK. Hệ thống thao tác trực tiếp lên DOM (thông qua ref hoặc canvas riêng) để vẽ hiệu ứng đồ họa 60FPS mà không gây ra hiện tượng Re-render toàn bộ cây DOM của React, đảm bảo hiệu năng tối đa.")

    add_heading(doc, "3.7.4 Phân hệ Dashboard Tổng quan (Analytics Dashboard)", 2)
    add_bullet(doc, "Trang hiển thị: AdminDashboardPage.tsx")
    add_bullet(doc, "Trực quan hóa dữ liệu: Tổng hợp các chỉ số quan trọng (KPIs) như Tổng số giáo viên, Tổng số khóa học đang hoạt động.")
    add_bullet(doc, "Nhật ký hoạt động (Activity Logs): Component này hiển thị dòng thời gian (Timeline) các thao tác gần nhất trên hệ thống (Ví dụ: \"Giáo viên A vừa cập nhật bài giảng B\"). Điều này giúp Admin giám sát chặt chẽ mọi thay đổi dữ liệu.")

    add_heading(doc, "3.7.5 Phân hệ Xác thực và Bảo mật (Authentication Module)", 2)
    add_paragraph(doc, "Phân hệ này được thiết kế như một hệ thống kiểm soát truy cập toàn diện, sử dụng kiến trúc tập trung dựa trên AuthContext.")
    add_bullet(doc, "Quản lý trạng thái: Lưu trữ các thông tin cốt lõi gồm đối tượng người dùng, trạng thái isAuthenticated và trạng thái isLoading để ngăn chặn hiện tượng nháy trang khi chưa khởi tạo xong phiên làm việc.")
    add_bullet(doc, "Đồng bộ phiên (Hydration): Khi người dùng tải lại trang (F5), hệ thống tự động truy xuất accessToken từ LocalStorage để khôi phục trạng thái đăng nhập, đảm bảo trải nghiệm không bị gián đoạn.")
    add_bullet(doc, "Bảo vệ luồng truy cập (Route Guarding): Sử dụng cơ chế Private Route Wrapper để bọc các trang dành riêng cho giáo viên. Nếu người dùng chưa xác thực, hệ thống sẽ cưỡng chế điều hướng về trang đăng nhập.")

    add_heading(doc, "3.7.6 Phân hệ Cổng thông tin Giáo viên (Teacher Portal)", 2)
    add_paragraph(doc, "Đảm nhiệm vai trò điều hướng và giúp giáo viên tiếp cận tài liệu giảng dạy thông qua lộ trình 3 bước: Trang chủ > Chọn chương trình > Danh sách khóa học.")
    add_bullet(doc, "Thiết kế đáp ứng (Responsive Grid): Sử dụng CSS Grid với hàm repeat (auto-fill, minmax (300px, 1fr)) giúp giao diện tự động thích ứng với nhiều kích thước màn hình từ máy chiếu đến máy tính bảng.")
    add_bullet(doc, "Lọc dữ liệu phía Client: Tích hợp tính năng tìm kiếm và lọc theo cấp độ ngay tại trình duyệt thông qua useMemo, giúp loại bỏ độ trễ mạng và mang lại phản hồi tức thì cho người dùng.")

    add_heading(doc, "3.7.7 Trình phát bài giảng tương tác (Interactive Lesson Player)", 2)
    add_paragraph(doc, "Đây là tính năng cốt lõi, thay thế các công cụ trình chiếu truyền thống bằng một môi trường thực thi bài giảng trực tiếp trên trình duyệt.")
    add_bullet(doc, "Kiến trúc chuyển đổi nội dung: Áp dụng mô hình StageRenderer để hiển thị nội dung dựa trên 8 bước sư phạm chuẩn (Mục tiêu, Tổng quan, Lắp ráp PDF, Video, Quiz...) mà không cần tải lại trang.")
    add_bullet(doc, "Tối ưu hóa trình chiếu Slide: Sử dụng kỹ thuật Smart Pre-fetching (tải trước ảnh slide tiếp theo vào bộ nhớ đệm) để đảm bảo độ trễ bằng không khi giáo viên chuyển trang.")
    add_bullet(doc, "Quản lý Video thông minh: Trình phát video tùy chỉnh có khả năng ghi nhớ mốc thời gian (savedVideoTime) khi người dùng chuyển đổi giữa các tab nội dung, cho phép tiếp tục xem video tại đúng vị trí cũ khi quay lại.")

    add_heading(doc, "3.8 CÁC TÍNH NĂNG MỞ RỘNG VÀ TỐI ƯU HÓA HỆ THỐNG", 1)
    add_paragraph(doc, "Giai đoạn 2 của dự án tập trung vào việc nâng cấp sâu về mặt kiến trúc, tối ưu hiệu năng và phát triển các tính năng đột phá, giúp chuyển đổi hệ thống từ một trang web quản lý thông thường thành một nền tảng giáo dục thông minh (EdTech Platform). Dưới đây là phân tích chi tiết về thiết kế kỹ thuật cho các tính năng mở rộng này.")

    add_heading(doc, "3.8.1 Thiết kế Bảo mật Tầng Dữ liệu với Row Level Security (RLS)", 2)
    add_paragraph(doc, "Thay vì chỉ dựa vào phân quyền ở tầng ứng dụng (Application Layer), hệ thống áp dụng cơ chế Row Level Security (RLS) của Supabase để chặn các rủi ro bảo mật từ gốc (Database Layer).")
    add_bullet(doc, "Kiến trúc xử lý: Mỗi request từ Client gửi lên Supabase đều kèm theo một JWT Token. Tại tầng PostgreSQL, các chính sách (Policies) sẽ giải mã token này để lấy auth.uid() và tiến hành đánh giá điều kiện trước khi cho phép đọc/ghi dữ liệu.")
    add_bullet(doc, "Logic phân quyền Học sinh: Bảng lessons và courses được gắn policy kiểm tra xem auth.uid() của học sinh có tồn tại trong bảng enrollments đối với khóa học tương ứng hay không. Nếu không, CSDL sẽ trả về mảng rỗng ngay lập tức, ngăn chặn hoàn toàn việc học sinh truy cập trái phép khóa học chưa đăng ký qua API.")
    add_bullet(doc, "Logic phân quyền Giáo viên: Áp dụng policy đối chiếu auth.uid() với cột teacher_id trong bảng assignments. Đảm bảo giáo viên chỉ có quyền truy cập và chấm điểm những lớp mình được phân công.")

    add_heading(doc, "3.8.2 Thiết kế Kiến trúc Đồng bộ Hóa Thời gian thực (Real-time Sync)", 2)
    add_paragraph(doc, "Bài toán đặt ra là làm sao giáo viên nhận được thông báo ngay lập tức khi được admin phân công lớp mới mà không cần phải thực hiện thao tác F5 (tải lại trang) hay hệ thống phải gọi API liên tục (Polling).")
    add_bullet(doc, "Giao thức sử dụng: Sử dụng WebSockets thông qua hệ thống Realtime của Supabase, lắng nghe trực tiếp luồng thay đổi dữ liệu (Replication Stream) của PostgreSQL.")
    add_bullet(doc, "Logic xử lý tại Frontend: Tại AuthContext hoặc các Hook quản lý trạng thái, một Channel được khởi tạo để lắng nghe sự kiện INSERT trên bảng assignments. Dữ liệu trả về sẽ được lọc (filter) tại Client: nếu teacher_id khớp với người dùng hiện tại, hệ thống sẽ kích hoạt một hàm Toast Notification (thông báo nổi) và tự động gọi lại hàm fetch để cập nhật danh sách khóa học, mang lại trải nghiệm liền mạch.")

    add_heading(doc, "3.8.3 Kỹ thuật Tối ưu Hiệu năng (Data Aggregation & N+1 Query)", 2)
    add_paragraph(doc, "Trong kiến trúc cũ, để tải toàn bộ nội dung của một bài học (gồm thông tin chung, mục tiêu, chuẩn bị, danh sách slide, video, quiz, challenge), Frontend phải thực hiện đồng thời nhiều request API độc lập, gây ra bài toán N+1 Query và làm tăng độ trễ (Latency).")
    add_bullet(doc, "Giải pháp Aggregation: Chuyển dịch tác vụ ghép nối dữ liệu (Data Joining) từ tầng Client/Node.js xuống thẳng tầng Cơ sở dữ liệu.")
    add_bullet(doc, "Triển khai RPC Function: Viết một hàm PostgreSQL (Stored Procedure/RPC) sử dụng các hàm JSON tích hợp sẵn như jsonb_build_object và json_agg. Hàm này thực hiện JOIN các bảng liên quan và đóng gói toàn bộ nội dung thành một JSON payload duy nhất trả về cho Client.")
    add_bullet(doc, "Đánh giá hiệu năng: Giải pháp này giảm số lượng request HTTP từ 6 xuống còn 1, giảm băng thông mạng và cắt giảm thời gian xử lý API xuống dưới 100ms, giúp trải nghiệm chuyển bài học của người dùng diễn ra tức thì.")

    add_heading(doc, "3.8.4 Kiến trúc tái sử dụng cho Cổng Tự học (Student Portal)", 2)
    add_paragraph(doc, "Cổng tự học dành cho học sinh yêu cầu hiển thị nội dung bài học giống như giao diện của giáo viên nhưng không được phép có các tính năng sửa, xóa hay quản lý.")
    add_bullet(doc, "Thiết kế Component đa hình (Polymorphic Components): Thay vì code lại một trang hoàn toàn mới, hệ thống tái sử dụng toàn bộ các component trình chiếu bài giảng (LessonContent, LessonVideo, LessonQuiz) nhưng thiết kế thêm một biến Prop: role=\"student\".")
    add_bullet(doc, "Render có điều kiện: Khi role=\"student\", các thành phần UI quản trị (như nút Edit, Delete) sẽ bị ẩn đi. Tại component Challenge, thay vì hiển thị danh sách bài nộp của học sinh (dành cho giáo viên), hệ thống sẽ render giao diện Nộp bài (Drag & Drop) dành riêng cho học sinh.")
    add_bullet(doc, "Theo dõi tiến độ (Progress Tracking): Tích hợp luồng ghi nhận dữ liệu vào bảng lesson_progress. Khi học sinh xem xong video hoặc nộp bài, Frontend sẽ trigger API cập nhật trạng thái (status: 'completed', score: ...), từ đó tính toán phần trăm hoàn thành khóa học.")

    add_heading(doc, "3.8.5 Thiết kế Luồng tương tác Nộp bài tệp đính kèm (.llsp3)", 2)
    add_paragraph(doc, "Để kết nối môi trường học tập lý thuyết với thực hành, hệ thống cho phép nộp file dự án lập trình từ phần mềm Lego SPIKE (.llsp3).")
    add_bullet(doc, "Xử lý Drag & Drop: Frontend xây dựng một vùng thả file (Dropzone) với các sự kiện onDragOver, onDrop. File tải lên được kiểm tra validation nghiêm ngặt về định dạng (.llsp3, .png, .jpg) và dung lượng (giới hạn 10MB) trước khi được xử lý.")
    add_bullet(doc, "Quản lý lưu trữ Storage: File được đẩy lên Supabase Storage thông qua API mã hóa Multipart. Hệ thống tạo đường dẫn thư mục theo định dạng student_id/lesson_id/filename để tránh xung đột tên file.")
    add_bullet(doc, "Ghi nhận tiến độ: Sau khi upload thành công, public URL của file sẽ được lưu vào thuộc tính submitted_file_url trong bảng lesson_progress, đóng vai trò như cầu nối để giáo viên có thể truy xuất và tải bài làm về chấm điểm.")

    add_heading(doc, "3.8.6 Kiến trúc Trợ lý AI Phân tích hình ảnh (AI Vision Tutor)", 2)
    add_paragraph(doc, "Nhằm giúp trẻ em tự giải quyết lỗi lập trình một cách độc lập, nền tảng tích hợp AI có khả năng thị giác (Vision AI) thông qua mô hình Gemini.")
    add_bullet(doc, "Luồng dữ liệu (Data Flow): Tại mục thử thách, học sinh nhấp vào tính năng \"Hỏi AI Trợ giảng\". Hệ thống cung cấp công cụ tải lên ảnh chụp màn hình khối lệnh bị lỗi. Ảnh được mã hóa sang dạng Base64 và đính kèm vào luồng chat.")
    add_bullet(doc, "Xử lý Backend AI: API Backend nhận ảnh và tin nhắn, sau đó ghép nối với một System Prompt được thiết kế chuyên biệt (Ví dụ: \"Đóng vai một gia sư hài hước, giải thích lỗi logic trong khối lệnh Lego...\"). Request được gửi đến Gemini API.")
    add_bullet(doc, "Phản hồi Stream: Thay vì đợi AI xử lý xong toàn bộ mới hiển thị, Backend sử dụng cơ chế Server-Sent Events (SSE) để trả về từng đoạn văn bản nhỏ (Streaming). Frontend nhận dữ liệu và tạo hiệu ứng gõ chữ (Typewriter effect) trực tiếp trên giao diện chat, mang lại cảm giác trò chuyện thực tế.")

    add_heading(doc, "3.8.7 Kỹ thuật Gamification (Hiệu ứng khen thưởng trực quan)", 2)
    add_paragraph(doc, "Gamification đóng vai trò quan trọng trong EdTech nhằm duy trì hứng thú và động lực của học sinh. Nền tảng ứng dụng điều này qua các hiệu ứng phần thưởng (Rewards).")
    add_bullet(doc, "Kiến trúc tích hợp: Sử dụng thư viện canvas-confetti kết hợp với các hoạt ảnh GSAP để tạo hiệu ứng pháo hoa và bóng bay.")
    add_bullet(doc, "Luồng thực thi Non-blocking: Để không làm gián đoạn trải nghiệm người dùng, hiệu ứng được kích hoạt (trigger) độc lập thông qua Callback Function ngay khi API nộp bài (submit) trả về mã 200 OK. Hệ thống thao tác trực tiếp lên DOM (thông qua ref hoặc canvas riêng) để vẽ hiệu ứng đồ họa 60FPS mà không gây ra hiện tượng Re-render toàn bộ cây DOM của React, đảm bảo hiệu năng tối đa.")

    output_path = "Chuong3_PhanTichThietKe.docx"
    doc.save(output_path)
    print(f"File created successfully at {output_path}")

if __name__ == "__main__":
    create_chuong3()
